#docker-compose build
version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      gpudb-net:
        ipv4_address: 172.20.0.8
  kafka: #build local docker image
    build:
      context: .
      dockerfile: Dockerfile.kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.0.9
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      gpudb-net:
        ipv4_address: 172.20.0.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kagent:
    image: kinetica/kagent:latest
    ports:
      - "18081:8081"
    networks:
      - gpudb-net
  gpudb-head:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: donstewart/ubuntu:18.04-ssh
    expose:
      - "22"
    ports:
      - "48080:8080"
      - "48088:8088"
      - "49191:9191"
    tty: true
    networks:
      gpudb-net:
        ipv4_address: 172.20.0.10
  gpudb-worker:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    image: donstewart/ubuntu:18.04-ssh
    expose:
      - "22"
    ports:
      - "38080:8080"
      - "38088:8088"
      - "39191:9191"
    tty: true
    networks:
      gpudb-net:
        ipv4_address: 172.20.0.20

networks:
  gpudb-net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

secrets:  
  host_ssh_key:
    file: ~/.ssh/id_rsa